---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
  labels:
    app: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      imagePullSecrets:
      - name: mygithub.com-token
      containers:
      - name: mediawiki
        image: vedprakashnimbalkar/mediawikiapp:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
spec:
  selector:
    app: mediawiki
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediawiki-ingress
  namespace: mediawiki-service
spec:
  rules:
  - host: assignment.com
    http:
      paths: 
      - path: /var/www/mediawiki
        pathType: Prefix
        backend:
          service:
            name: mediawiki-service
            port:
              number: 31000
